spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.79/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell
#---------------application.yml  -------Using the logback
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: E:/var/log/tomcat/
#  file: E:/var/log/tomcat/sell.log
#  level:
#    com.miso.LoggerTest: debug



