spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///springboot
    username: root
    password: root
  jpa:
    show-sql: true
server:
  context-path: /sell
#---------------在application.yml中配置日志
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: E:/var/log/tomcat/
#  file: E:/var/log/tomcat/sell.log
#  level:
#    com.miso.LoggerTest: debug


