spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.79/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell
  port: 80
#---------------application.yml  -------Using the logback
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: E:/var/log/tomcat/
#  file: E:/var/log/tomcat/sell.log
#  level:
#    com.miso.LoggerTest: debug

#配置微信平台
wechat:
  mpAppId: wxe97fa21bb576e886
  mpAppSecert: 207e9d968ab51c28299bef0237952296
#  mchId: 1409146202
#  mchKey: c976503d34ca432c601361f969fd8d85
#  keyPath:



